import assert from 'node:assert/strict';
const base = process.env.TEST_API_URL;
if (!base || new URL(base).hostname !== '127.0.0.1' || new URL(base).port !== '53101') throw Error('Local test API only');
const call = async (path: string, method='GET', body?: unknown, authorized=true) => {
  const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(authorized?{'x-internal-secret':'local-cms-test-only'}:{})},body:body?JSON.stringify(body):undefined});
  return {status:r.status,body:await r.json()};
};
assert.equal((await call('/internal/program','GET',undefined,false)).status,403);
const snapshot=await call('/internal/app-content'); assert.equal(snapshot.status,200);
const changed=await call('/internal/app-content','PUT',{expectedVersion:snapshot.body.version,patch:{city:'Тестовый город'},reason:'Локальная проверка сохранения'}); assert.equal(changed.status,200);
assert.equal((await call('/app-content')).body.city,'Тестовый город');
assert.equal((await call('/internal/app-content','PUT',{expectedVersion:snapshot.body.version,patch:{city:'Нельзя перезаписать'},reason:'Старая вкладка'})).status,409);
assert.equal((await call('/internal/app-content','PUT',{city:'Старый клиент'})).status,428);
assert.equal((await call('/internal/app-content/history')).body[0].version,changed.body.version);
const restored=await call('/internal/app-content','PUT',{expectedVersion:changed.body.version,patch:{city:snapshot.body.data.city},reason:'Отмена локальной проверки'}); assert.equal(restored.status,200);
const create=await call('/internal/sessions','POST',{title:'Локальный тест модераторов',description:'Проверка',dayId:'test-day',hallId:'test-hall',trackId:'t_ai',startTime:'10:00',endTime:'11:00',speakerIds:['test-speaker'],moderatorIds:['test-speaker']});
assert.equal(create.status,201); const id=create.body.id;
const program=await call('/internal/program');
assert.deepEqual(program.body.sessions.find((s:{id:string})=>s.id===id).moderatorIds,['test-speaker']);
assert.equal((await call('/sessions')).body.some((s:{id:string})=>s.id===id),false,'New session must remain a draft');
assert.equal((await call('/internal/sessions/'+id,'PUT',{moderatorIds:[]})).status,200);
assert.deepEqual((await call('/internal/program')).body.sessions.find((s:{id:string})=>s.id===id).moderatorIds,[]);
assert.equal((await call('/internal/sessions/'+id,'PUT',{title:'Must not persist',moderatorIds:['missing-speaker']})).status,409);
assert.equal((await call('/internal/program')).body.sessions.find((s:{id:string})=>s.id===id).title,'Локальный тест модераторов');
assert.equal((await call('/internal/sessions/'+id,'PUT',{isPublished:true})).status,400);
assert.equal((await call('/internal/sessions/'+id,'DELETE')).status,405);
assert.equal((await call('/internal/content-health')).status,200);
assert.equal((await call('/internal/push-status')).body.verifiedUsers,0);
console.log('PASS: auth guard, content save/read, stale save, legacy rejection, history, undo, moderator create/read/clear, atomic rollback, draft visibility, publication boundary, push diagnostics');
